### PR TITLE
Add Bacon Maintainer

### PR DESCRIPTION
**Pull request by alistairholmes**
Added OnePlus One(bacon) maintainer.

### CODE REVIEW

**Review by akhilnarang — CHANGES_REQUESTED** [review]
OnePlus One please, haven't seen it as OnePlus '1' Anywhere :p

**Comment by alistairholmes** [comment]
Thanks, I have made the necessary changes to the file.

Below is a Link to the commit:
https://github.com/OwnROM/android_packages_apps_OwnSettings/pull/2/commits/b544234016f83587253c9223aba1aa5323806d40

**Review by akhilnarang — APPROVED** [review]

**Review by OwnDroid — COMMENTED** [review]
Now it's complete ;)

**Comment by alistairholmes** [comment]
Awesome ;)

**Pull request merged**
